pipeline {
  agent any
  tools {
    maven 'Maven 3.6.3'
  }

  stages{
    stage('build'){
      steps{
        echo 'Compiling worker app'
        dir('worker'){
          sh 'mvn compile'
        }
      }
    }
    stage('test'){
      steps{
        echo 'Running Unit tests on worker app'
        dir('worker'){
          sh 'mvn clean test'
        }
      }
    }
    stage('package'){
      steps{
        echo 'Packing worker app'
        dir('worker'){
          sh 'mvn package'
        }
      }
    }
  }
  post {
    always{
      echo 'Pipeline successfully'
    }
  }
}